name: Tests and Linting

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Install
        run: yarn install

      - name: Typecheck
        run: yarn x tsc

      - name: Test
        run: yarn x test --coverage

      - name: Upload Coverage Report
        uses: actions/upload-artifact@v2
        with:
          name: coverage-report
          path: packages/xstate-compiled/coverage
