# https://github.com/marketplace/actions/automatic-rebase  (https://github.com/cirrus-actions/rebase)
name: Snapshot Release

on: pull_request

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: 12.x

      - name: Install dependencies
        run: yarn

      - name: Prepare artifacts
        run: yarn build

      - name: Release a snapshot
        run: |
          yarn changeset version --snapshot
          yarn changeset publish --tag pr
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
